# Generated by Django 4.2.2 on 2023-06-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[(1, 'bardzo ważny'), (2, 'ważny'), (3, 'neutralny')], max_length=10)),
            ],
        ),
    ]
