# Generated by Django 4.2.2 on 2023-06-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertpost',
            name='category',
            field=models.CharField(choices=[(1, 'bardzo ważny'), (2, 'ważny'), (3, 'neutralny')], max_length=1),
        ),
    ]
