# Generated by Django 4.2.2 on 2023-06-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_alter_advertpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertpost',
            name='category',
            field=models.CharField(choices=[('1', 'bardzo ważny'), ('2', 'ważny'), ('3', 'neutralny')], max_length=15),
        ),
    ]
